@startuml

@startuml

Electrode <|-- PElectrode
Electrode <|-- NElectrode
BatteryCell *-- Electrode
BatteryCell *-- Electrolyte

BaseCycler <|--- Discharge
BaseCycler <|--- DischargeRest
BaseCycler <|--- Charge
BaseCycler <|-left ChargeDischarge
BaseCycler <|-- CustomCycler


BaseElectrodeConcSolver <|-- PolynomialSolver

BatterySolver *-- BaseElectrodeConcSolver
BatterySolver *-- BatteryCell
BatterySolver *-- BaseCycler

BatterySolver *- SPModel
BatterySolver *-- LumpedThermalModel

ROMSEI *- ROMSEISolver
BatterySolver *-- ROMSEISolver

@enduml

@enduml