@startuml

Electrode <|-- PElectrode
Electrode <|-- NElectrode
BatteryCell *-- Electrode
BatteryCell *-- Electrolyte

BaseCycler <|--- Discharge
BaseCycler <|--- DischargeRest
BaseCycler <|--- Charge
BaseCycler <|-left ChargeDischarge
BaseCycler <|-- CustomCycler
CustomCycler <|--- HPPCCyler
CustomCycler <|--- DSTCycler

BaseElectrodeConcSolver <|-- PolynomialSolver
BaseElectrodeConcSolver <|-- EigenSolver
BaseElectrodeConcSolver <|-- CNSolver

class ElectrolyteFVMCordinates
class ElectrolyteConcFVMSolver

SPSolver *-- BaseElectrodeConcSolver
SPSolver *-- BatteryCell
SPSolver *-- BaseCycler

SPSolver *- ESPModel
SPSolver *-- LumpedThermalModel
SPSolver *---right ROMSEI


@enduml