# Generated by Django 4.2.7 on 2023-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=200)),
                ('battery_cell_model', models.CharField(max_length=200)),
                ('solver_type', models.CharField(max_length=200)),
                ('cycler', models.CharField(max_length=200)),
            ],
        ),
    ]
